<?php

namespace AdminBundle\Repository;

/**
 * DiseasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiseasesRepository extends \Doctrine\ORM\EntityRepository
{
}
