<?php

namespace AdminBundle\Repository;

/**
 * SupplementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementsRepository extends \Doctrine\ORM\EntityRepository
{
}
