<?php

namespace AdminBundle\Repository;

/**
 * TherapyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TherapyRepository extends \Doctrine\ORM\EntityRepository
{
}
