<?php

namespace AdminBundle\Repository;

/**
 * TherapistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TherapistRepository extends \Doctrine\ORM\EntityRepository
{
}
